### PR TITLE
Different parchment and font

### PR DESCRIPTION
**Pull request by gynt**
Parchment is definitely an improvement.

Font I am not 100% sure, maybe too thin?

### CODE REVIEW

**Comment by TheRedDaemon** [comment]
From where did you get the fonts? Are they open for any usage?

**Comment by gynt** [comment]
https://www.dafont.com/de/day-roman.font?text=This+module+allows+to+switch+the+displaying+system+to+a+more+modern+that+use&psize=xs&back=theme
https://www.dafont.com/de/day-roman.font?text=This+module+allows+to+switch+the+displaying+system+to+a+more+modern+that+use&psize=xs&back=theme

**Comment by TheRedDaemon** [comment]
Seems the authors have gone missing or something. Found a link to [THIS](https://web.archive.org/web/20150316222608/http://apostrophiclab.pedroreina.net/info.html) in the comments (with a lot of the others asking regarding commercial use). Was there any license attached to the download? If not, I would assume one would have consider this infi text as license. Part of me says that this would not fly with big projects. For us, it should be ok I guess, Iam just wondering if, what and where we include the license info...

**Comment by gynt** [comment]
For River Avenue:
[legal_rv.txt](https://github.com/UnofficialCrusaderPatch/UCP3-GUI/files/13849963/legal_rv.txt)

And this is for DAYROM, look at the last few sentences.
[DAY-O.txt](https://github.com/UnofficialCrusaderPatch/UCP3-GUI/files/13849965/DAY-O.txt)

**Comment by TheRedDaemon** [comment]
Seems fine to me, one is some copyleft license, but we use a very strict one anyway, so there should be no issues. The other is fine enough. Now Inalways wonder if having these text files in the source would be enough, or if we ned to but them somewhere reachable in the GUI... I would assume the former.

**Pull request merged**
